name: Bundle VSCode extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Extension version tag'
        default: 'vscode-v0.0.0'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Compile server
        run: dotnet build server/Oraide.LanguageServer.sln
      #  run: |
      #    mkdir -p build/server
      #    dotnet build server/Oraide.LanguageServer.sln

      - name: Copy server
        run: |
          mkdir clients/oraide-vscode/bin
          cp -r server/bin/* clients/oraide-vscode/bin
      
      - name: Package VS Code extension
        uses: nhedger/package-vscode-extension@v1

      - name: Bundle release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: "${{ github.event.inputs.version }}.zip"
          directory: server/bin

      - name: Upload Package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          file_glob: true
          file: server/bin/${{ github.event.inputs.version }}.zip
